/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senac.sp.pi;

import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author denis.lsilva9
 */
public class CadastroCliente extends javax.swing.JPanel {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        
    }

    public ButtonGroup getGrupoGenero() {
        return GrupoGenero;
    }

    public void setGrupoGenero(ButtonGroup GrupoGenero) {
        this.GrupoGenero = GrupoGenero;
    }

    public JRadioButton getBtnGenFeminino() {
        return btnGenFeminino;
    }

    public void setBtnGenFeminino(JRadioButton btnGenFeminino) {
        this.btnGenFeminino = btnGenFeminino;
    }

    public JRadioButton getBtnGenMasculino() {
        return btnGenMasculino;
    }

    public void setBtnGenMasculino(JRadioButton btnGenMasculino) {
        this.btnGenMasculino = btnGenMasculino;
    }

    public JRadioButton getBtnGenOutros() {
        return btnGenOutros;
    }

    public void setBtnGenOutros(JRadioButton btnGenOutros) {
        this.btnGenOutros = btnGenOutros;
    }

    public JFormattedTextField getValorCEP() {
        return valorCEP;
    }

    public void setValorCEP(JFormattedTextField valorCEP) {
        this.valorCEP = valorCEP;
    }

    public JFormattedTextField getValorCPF() {
        return valorCPF;
    }

    public void setValorCPF(JFormattedTextField valorCPF) {
        this.valorCPF = valorCPF;
    }

    public JFormattedTextField getValorDataNascimento() {
        return valorDataNascimento;
    }

    public void setValorDataNascimento(JFormattedTextField valorDataNascimento) {
        this.valorDataNascimento = valorDataNascimento;
    }

    public JTextField getValorEmail() {
        return valorEmail;
    }

    public void setValorEmail(JTextField valorEmail) {
        this.valorEmail = valorEmail;
    }

    public JTextField getValorEstado() {
        return valorEstado;
    }

    public void setValorEstado(JFormattedTextField valorEstado) {
        this.valorEstado = valorEstado;
    }

    public JTextField getValorNome() {
        return valorNome;
    }

    public void setValorNome(JTextField valorNome) {
        this.valorNome = valorNome;
    }

    public JTextField getValorRua() {
        return valorRua;
    }

    public void setValorRua(JTextField valorRua) {
        this.valorRua = valorRua;
    }

    public JFormattedTextField getValorTelefone() {
        return valorTelefone;
    }

    public JTextField getValorBairro() {
        return valorBairro;
    }

    public void setValorBairro(JTextField valorBairro) {
        this.valorBairro = valorBairro;
    }

    public JLabel getValorNumero() {
        return valorNumero;
    }

    public void setValorNumero(JLabel valorNumero) {
        this.valorNumero = valorNumero;
    }

    public void setValorTelefone(JFormattedTextField valorTelefone) {
        this.valorTelefone = valorTelefone;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        GrupoGenero = new javax.swing.ButtonGroup();
        label = new javax.swing.JLabel();
        btnGenFeminino = new javax.swing.JRadioButton();
        btnGenMasculino = new javax.swing.JRadioButton();
        btnGenOutros = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        valorNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        valorCEP = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        valorRua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        valorTelefone = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valorCPF = new javax.swing.JFormattedTextField();
        valorEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        valorDataNascimento = new javax.swing.JFormattedTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        valorNumero = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        valorBairro = new javax.swing.JTextField();
        valorEstado = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();

        jScrollPane1.setViewportView(jTree1);

        jFormattedTextField1.setText("jFormattedTextField1");
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabel9.setText("jLabel9");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        label.setText("CPF:");

        GrupoGenero.add(btnGenFeminino);
        btnGenFeminino.setText("Feminino");
        btnGenFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenFemininoActionPerformed(evt);
            }
        });

        GrupoGenero.add(btnGenMasculino);
        btnGenMasculino.setText("Masculino");

        GrupoGenero.add(btnGenOutros);
        btnGenOutros.setText("Outros");

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone (DDD):");

        jLabel7.setText("CEP:");

        try {
            valorCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        valorCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorCEPActionPerformed(evt);
            }
        });

        jLabel8.setText("Rua:");

        jLabel10.setText("Estado:");

        try {
            valorTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Email:");

        jLabel4.setText("Genero:");

        try {
            valorCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        valorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorEmailActionPerformed(evt);
            }
        });

        jLabel6.setText("Data de Nascimento (DD/MM/AAAA):");

        try {
            valorDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        valorNumero.setText("Número");

        jLabel5.setText("Bairro:");

        try {
            valorEstado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorNome)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(valorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(valorTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                                .addComponent(valorRua)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(valorCEP)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(valorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(2, 2, 2))
                                                .addComponent(valorEmail))
                                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(132, 132, 132)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(valorBairro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnGenFeminino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnGenMasculino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnGenOutros))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(valorDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(btnConfirmar)
                        .addGap(26, 26, 26)
                        .addComponent(btnCancelar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valorNumero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(valorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(valorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(valorCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(valorEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(valorRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorNumero)
                    .addComponent(jLabel5)
                    .addComponent(valorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnGenFeminino)
                    .addComponent(btnGenMasculino)
                    .addComponent(btnGenOutros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(valorDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void btnGenFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenFemininoActionPerformed

    private void valorCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorCEPActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
            // TODO add your handling code here:
             String nome = valorNome.getText();
             String rua = valorRua.getText();
             String cpf = valorCPF.getText();
             String dn = valorDataNascimento.getText();
             String cep = valorCEP.getText();
             String numero = valorNumero.getText();
             String bairro = valorBairro.getText();
             String estado = valorEstado.getText();
             
             try{
                 if(nome.equals("") || rua.equals("") || cpf.equals("")  || dn.equals("")  || cep.equals("")  || numero.equals("")  || bairro.equals("")  || estado.equals("") || btnGenFeminino.isSelected() != true || btnGenMasculino.isSelected() != true || btnGenOutros.isSelected() != true )
                     JOptionPane.showMessageDialog(null, "Campos Válidos");
                     
             } catch(NumberFormatException e) {
                 JOptionPane.showMessageDialog(null, "Campos Inválidos");
             }
             
             
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void valorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoGenero;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JRadioButton btnGenFeminino;
    private javax.swing.JRadioButton btnGenMasculino;
    private javax.swing.JRadioButton btnGenOutros;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField valorBairro;
    private javax.swing.JFormattedTextField valorCEP;
    private javax.swing.JFormattedTextField valorCPF;
    private javax.swing.JFormattedTextField valorDataNascimento;
    private javax.swing.JTextField valorEmail;
    private javax.swing.JFormattedTextField valorEstado;
    private javax.swing.JTextField valorNome;
    private javax.swing.JLabel valorNumero;
    private javax.swing.JTextField valorRua;
    private javax.swing.JFormattedTextField valorTelefone;
    // End of variables declaration//GEN-END:variables
}
