
package br.senac.sp.pi.view;


import java.util.Calendar;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Matheus
 */
public class TelaRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form telaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
        String dataInicio;
        String dataFinal;
        int idCompra;
        double valorCompra;
        String nomeCliente;
        double valoTotal;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }


    public JLabel getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(JLabel valorTotal) {
        this.valorTotal = valorTotal;
    }


    public void setDatafield2(JFormattedTextField datafield2) {
        this.datafield2 = datafield2;
    }

    public JFormattedTextField getDatafield2() {
        return datafield2;
    }

    public JFormattedTextField getDatafield1() {
        return datafield1;
    }

    public void setDatafield1(JFormattedTextField datafield1) {
        this.datafield1 = datafield1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datafield1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        datafield2 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        valorTotal = new javax.swing.JLabel();
        filtrarData = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        datafield1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        datafield1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datafield1.setToolTipText("dd/mm/yyyy");
        datafield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafield1ActionPerformed(evt);
            }
        });

        jLabel1.setText("até");

        datafield2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        datafield2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datafield2.setToolTipText("dd/mm/yyyy");
        datafield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datafield2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Total das vendas dentro do período:");

        valorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valorTotal.setText("R$00,00");

        filtrarData.setText("Filtrar");
        filtrarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarDataActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Compra", "Nome do Cliente", "Valor da Compra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel4.setText("Data Inicial");

        jLabel5.setText("Data Final");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(datafield1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(datafield2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filtrarData)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorTotal)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(datafield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(datafield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(filtrarData)
                                .addComponent(jLabel2)
                                .addComponent(valorTotal)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datafield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datafield2ActionPerformed

    private void filtrarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarDataActionPerformed
        Date d = new Date();
        Calendar c = Calendar.getInstance();
        String dataAtual = c.get(Calendar.DAY_OF_MONTH) + "/" + c.get(Calendar.MONTH) + "/" + c.get(Calendar.YEAR); 
        int today = c.get(Calendar.DAY_OF_MONTH);
        int actualMonth = c.get(Calendar.MONTH) + 1;
        int actualYear = Integer.parseInt(Integer.toString(c.get(Calendar.YEAR)).substring(2,4) );
        
        String dateStart = datafield1.getText();
        String dateEnd = datafield2.getText();
        if(dateStart.isEmpty() || dateEnd.isEmpty()){
            JOptionPane.showMessageDialog(null, "Você precisa selecionar uma data de começo e de fim");
        }else{
              int diaInicio = Integer.parseInt(dateStart.substring(0,2));
                int mesInicio = Integer.parseInt(dateStart.substring(3,5));
                int diaFinal = Integer.parseInt(dateEnd.substring(0,2));
                int mesFinal = Integer.parseInt(dateEnd.substring(3,5));
                int anoInicio = Integer.parseInt(dateStart.substring(6,8));
                int anoFinal = Integer.parseInt(dateEnd.substring(6,8));
            if( (actualYear < anoFinal || actualYear < anoInicio) || ( (actualYear <= anoFinal && actualMonth < mesFinal) || (actualYear <= anoInicio && actualMonth < mesInicio) ) ){
                System.out.println(today);
                System.out.println(actualMonth);
                System.out.println(mesFinal);
                JOptionPane.showMessageDialog(null, "Você não pode selecionar uma data superior que a data atual");
            }
            else{

                //int anoComeco = Integer.parserInt(dateStart.substring());

                int mesTotal = mesFinal - mesInicio;
                int diasTotais = diaFinal - diaInicio;
                int anoTotal = anoFinal - anoInicio;

                if( ( (mesTotal == 0 && (diasTotais <=30 && diasTotais >=0) ) || (diasTotais <= 0 && mesTotal == 1) ) && anoTotal == 0){

                       JOptionPane.showMessageDialog(null, "Começo da data: " + dateStart + "\n"
                    + "Final da data: " + dateEnd);
                }else if(anoTotal == 1 && mesTotal == -11 && diasTotais <= 0){
                       JOptionPane.showMessageDialog(null, "Começo da data: " + dateStart + "\n"
                    + "Final da data: " + dateEnd);
                }else if(mesTotal < 0 || anoTotal < 0 || diasTotais < 0){
                       JOptionPane.showMessageDialog(null, "Período selecionado inválido!");
                }else{

                    JOptionPane.showMessageDialog(null, "Período selecionado maior que 30 dias!");
                }
            }
         
        }
    }//GEN-LAST:event_filtrarDataActionPerformed

    private void datafield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datafield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datafield1ActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        int row = jTable1.getSelectedRow();
        //String idCompra = jTable1.getModel().getValueAt(row,0).toString();
        System.out.println(row);
        //int idCompra = Integer.parseInt((String) jTable1.getModel().getValueAt(row,0));
        new TelaRelatorioAnalitico().setVisible(true);
        
    }//GEN-LAST:event_jTable1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField datafield1;
    private javax.swing.JFormattedTextField datafield2;
    private javax.swing.JButton filtrarData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables

}
