/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senac.sp.pi.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Talles
 */
public class TelaVendaProduto extends javax.swing.JFrame {
    

    /**
     * Creates new form TelaVendaProduto
     */
    public TelaVendaProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelTelaVenda = new javax.swing.JPanel();
        panelAdicionarProdutos = new javax.swing.JPanel();
        lblNomeCodProd = new javax.swing.JLabel();
        txtPesquisaProduto = new javax.swing.JTextField();
        spAdicionarProdutos = new javax.swing.JScrollPane();
        tblAdicionarProdutos = new javax.swing.JTable();
        lblQtd = new javax.swing.JLabel();
        btnAdicionarProdutos = new javax.swing.JButton();
        btnPesquisaProduto = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JFormattedTextField();
        panelCarrinhoDeCompras = new javax.swing.JPanel();
        spCarrinhoDeCompras = new javax.swing.JScrollPane();
        tblCarrinhoDeCompras = new javax.swing.JTable();
        btnExcluirItem = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        lblClienteCarrinho = new javax.swing.JLabel();
        panelTotal = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        panelTotalDeItens = new javax.swing.JPanel();
        lblTotalDeItens = new javax.swing.JLabel();
        panelFormaDePagamento = new javax.swing.JPanel();
        rdDebito = new javax.swing.JRadioButton();
        rdCredito = new javax.swing.JRadioButton();
        rdPix = new javax.swing.JRadioButton();
        rdDinheiro = new javax.swing.JRadioButton();
        btnFinalizarCompra = new javax.swing.JButton();
        panelConsultaDeCliente = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        btnPesquisaCliente = new javax.swing.JButton();
        txtCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        panelTelaVenda.setAlignmentX(0.0F);
        panelTelaVenda.setAlignmentY(0.0F);
        panelTelaVenda.setPreferredSize(new java.awt.Dimension(1196, 769));

        panelAdicionarProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5), "Adicionar produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N

        lblNomeCodProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNomeCodProd.setText("NOME/CÓDIGO DO PRODUTO:");

        txtPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaProdutoActionPerformed(evt);
            }
        });

        tblAdicionarProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Peça", "Cor", "Tamanho", "Preço", "Qtd em estoque"
            }
        ));
        spAdicionarProdutos.setViewportView(tblAdicionarProdutos);

        lblQtd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQtd.setText("QUANTIDADE:");

        btnAdicionarProdutos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionarProdutos.setText("ADICIONAR AO CARRINHO DE COMPRAS\n");
        btnAdicionarProdutos.setBorderPainted(false);
        btnAdicionarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutosActionPerformed(evt);
            }
        });

        btnPesquisaProduto.setToolTipText("");
        btnPesquisaProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaProdutoActionPerformed(evt);
            }
        });

        txtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####################"))));
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdicionarProdutosLayout = new javax.swing.GroupLayout(panelAdicionarProdutos);
        panelAdicionarProdutos.setLayout(panelAdicionarProdutosLayout);
        panelAdicionarProdutosLayout.setHorizontalGroup(
            panelAdicionarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdicionarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeCodProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisaProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(panelAdicionarProdutosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblQtd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidade)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelAdicionarProdutosLayout.createSequentialGroup()
                .addComponent(spAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAdicionarProdutosLayout.setVerticalGroup(
            panelAdicionarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdicionarProdutosLayout.createSequentialGroup()
                .addGroup(panelAdicionarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdicionarProdutosLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panelAdicionarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeCodProd)
                            .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelAdicionarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdicionarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelCarrinhoDeCompras.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true), "Carrinho de compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N

        spCarrinhoDeCompras.setBackground(new java.awt.Color(204, 204, 204));

        tblCarrinhoDeCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Peça", "Cor", "Tamanho", "Preço", "Qtd", "Total"
            }
        ));
        spCarrinhoDeCompras.setViewportView(tblCarrinhoDeCompras);

        btnExcluirItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirItem.setText("Excluir item");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCliente.setText("Cliente:");

        panelTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3), "TOTAL (R$)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTotalDeItens.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3), "TOTAL DE ITENS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        javax.swing.GroupLayout panelTotalDeItensLayout = new javax.swing.GroupLayout(panelTotalDeItens);
        panelTotalDeItens.setLayout(panelTotalDeItensLayout);
        panelTotalDeItensLayout.setHorizontalGroup(
            panelTotalDeItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalDeItensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTotalDeItensLayout.setVerticalGroup(
            panelTotalDeItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalDeItensLayout.createSequentialGroup()
                .addComponent(lblTotalDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelFormaDePagamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3), "FORMA DE PAGAMENTO\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        buttonGroup1.add(rdDebito);
        rdDebito.setText("Débito");

        buttonGroup1.add(rdCredito);
        rdCredito.setText("Crédito");

        buttonGroup1.add(rdPix);
        rdPix.setText("Pix");

        buttonGroup1.add(rdDinheiro);
        rdDinheiro.setText("Dinheiro");

        javax.swing.GroupLayout panelFormaDePagamentoLayout = new javax.swing.GroupLayout(panelFormaDePagamento);
        panelFormaDePagamento.setLayout(panelFormaDePagamentoLayout);
        panelFormaDePagamentoLayout.setHorizontalGroup(
            panelFormaDePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormaDePagamentoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(rdDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdPix, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFormaDePagamentoLayout.setVerticalGroup(
            panelFormaDePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormaDePagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormaDePagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdDebito)
                    .addComponent(rdCredito)
                    .addComponent(rdPix)
                    .addComponent(rdDinheiro))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnFinalizarCompra.setText("FINALIZAR COMPRA");

        javax.swing.GroupLayout panelCarrinhoDeComprasLayout = new javax.swing.GroupLayout(panelCarrinhoDeCompras);
        panelCarrinhoDeCompras.setLayout(panelCarrinhoDeComprasLayout);
        panelCarrinhoDeComprasLayout.setHorizontalGroup(
            panelCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spCarrinhoDeCompras, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelCarrinhoDeComprasLayout.createSequentialGroup()
                .addGroup(panelCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarrinhoDeComprasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCarrinhoDeComprasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCarrinhoDeComprasLayout.createSequentialGroup()
                                .addComponent(lblCliente)
                                .addGap(316, 316, 316)
                                .addComponent(lblClienteCarrinho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(panelFormaDePagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarrinhoDeComprasLayout.createSequentialGroup()
                                .addComponent(panelTotalDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCarrinhoDeComprasLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelCarrinhoDeComprasLayout.setVerticalGroup(
            panelCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarrinhoDeComprasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteCarrinho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCarrinhoDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCarrinhoDeComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotalDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConsultaDeCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5), "Consulta de cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(51, 51, 51))); // NOI18N
        panelConsultaDeCliente.setForeground(new java.awt.Color(255, 255, 255));

        lblCPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCPF.setText("CPF:");

        btnPesquisaCliente.setToolTipText("");
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultaDeClienteLayout = new javax.swing.GroupLayout(panelConsultaDeCliente);
        panelConsultaDeCliente.setLayout(panelConsultaDeClienteLayout);
        panelConsultaDeClienteLayout.setHorizontalGroup(
            panelConsultaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaDeClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF)
                .addGap(5, 5, 5)
                .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        panelConsultaDeClienteLayout.setVerticalGroup(
            panelConsultaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaDeClienteLayout.createSequentialGroup()
                .addGroup(panelConsultaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultaDeClienteLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelConsultaDeClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPF)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelConsultaDeClienteLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTelaVendaLayout = new javax.swing.GroupLayout(panelTelaVenda);
        panelTelaVenda.setLayout(panelTelaVendaLayout);
        panelTelaVendaLayout.setHorizontalGroup(
            panelTelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaVendaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAdicionarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelConsultaDeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCarrinhoDeCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTelaVendaLayout.setVerticalGroup(
            panelTelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaVendaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelTelaVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTelaVendaLayout.createSequentialGroup()
                        .addComponent(panelConsultaDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCarrinhoDeCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTelaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelTelaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed

        String cpf = txtCPF.getText().replaceAll("[^0-9]", "");

        if (cpf.isEmpty() || cpf.length() != 11){

            JOptionPane.showMessageDialog(this, "ERRO NO PREENCHIMENTO");

            txtLimpa();
        }

        else{

            JOptionPane.showMessageDialog(this,"- VERIFICA CADASTRO NO SISTEMA -");

            txtLimpa();
        }
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed

    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btnPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaProdutoActionPerformed

        String nomeCodigo = txtPesquisaProduto.getText();

        if(nomeCodigo.isEmpty()){

            JOptionPane.showMessageDialog(this, "ERRO: INSIRA UM VALOR");

        }
        else{
            JOptionPane.showMessageDialog(this, "- BUSCA O PRODUTO NO BANCO DE DADOS -");

            txtPesquisaProduto.setText("");

        }
    }//GEN-LAST:event_btnPesquisaProdutoActionPerformed

    private void btnAdicionarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutosActionPerformed

        
        //Erro de preenchimento
        
        
        String quantidade = txtQuantidade.getText();

        if(quantidade.isEmpty()){

            JOptionPane.showMessageDialog(this, "ERRO: INSIRA UM VALOR");

            txtLimpaQtd();
        }

        else{
            JOptionPane.showMessageDialog(this, quantidade + "  PRODUTO(S) ADICIONADO(S) AO CARRINHO!");

            txtLimpaQtd();
        }
    }//GEN-LAST:event_btnAdicionarProdutosActionPerformed

    private void txtPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaProdutoActionPerformed

    
    public void txtLimpa(){
    
    txtCPF.setValue(null);
}
    
    public void txtLimpaQtd(){
        
        txtQuantidade.setValue(null);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProdutos;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaProduto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblClienteCarrinho;
    private javax.swing.JLabel lblNomeCodProd;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDeItens;
    private javax.swing.JPanel panelAdicionarProdutos;
    private javax.swing.JPanel panelCarrinhoDeCompras;
    private javax.swing.JPanel panelConsultaDeCliente;
    private javax.swing.JPanel panelFormaDePagamento;
    private javax.swing.JPanel panelTelaVenda;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JPanel panelTotalDeItens;
    private javax.swing.JRadioButton rdCredito;
    private javax.swing.JRadioButton rdDebito;
    private javax.swing.JRadioButton rdDinheiro;
    private javax.swing.JRadioButton rdPix;
    private javax.swing.JScrollPane spAdicionarProdutos;
    private javax.swing.JScrollPane spCarrinhoDeCompras;
    private javax.swing.JTable tblAdicionarProdutos;
    private javax.swing.JTable tblCarrinhoDeCompras;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtPesquisaProduto;
    private javax.swing.JFormattedTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
